# Site Settings
theme_skin               : "dark"
locale                   : "en-US"
title                    : "Souheil TAIEB"
title_separator          : "-"
subtitle                 : "Software Engineer"
name                     : "Souheil TAIEB"
description              : >-
    I am a Software Enginner focusing on Web development and the .Net stack in particular.
    Technologies I’ve used includes .Net(C#), Sql/Transact Sql, ReactJs/Vue Js, and more.
    I blog about technology and engineering. Let's make the world better through hight quality software.

url                      :  "https://sotaieb.com"
baseurl                  :
logo                     : #"/assets/images/logo.png"
og_image                 : "/assets/images/staieb-tof.jpg"
masthead_title           : "Souheil TAIEB"
# breadcrumbs            : false # true, false (default)
words_per_minute         : 200
atom_feed:
  path                   : # blank (default) uses feed.xml

# head_scripts:
#   - https://xxx.min.js
#   - /assets/js/xxx.js

# footer_scripts:
#   - https://xxx.min.js
#   - /assets/js/xxx.js

# after_footer_scripts:
  #   - https://xxx.min.js
  #   - /assets/js/xxx.js

# SEO Related
google_site_verification : "OfqzMKz_ROfaV-fV5St63PcazqmveEpgj0yfPqXvNis"

# Social Sharing
twitter:
  username               : "sotaieb"

# Analytics
analytics:
  provider               : "google-gtag" #false "custom"

# Site Author
author:
  name             : "Souheil TAIEB"
  avatar           : "/assets/images/staieb-tof.jpg"

  bio              : >-
    I am a Software Enginner focusing on Web development and the .Net stack in particular.
    Technologies I’ve used includes .Net(C#), Sql/Transact Sql, ReactJs/Vue Js, and more.
    I blog about technology and engineering. Let's make the world better through hight quality software.
  location         : "France"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:sxtaieb@gmail.com"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://staieb.blogspot.com/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/sotaieb"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/sotaieb"

# Site Footer
footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:sxtaieb@gmail.com"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://staieb.blogspot.com/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/sotaieb"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/sotaieb"

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - vendor
  - local
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/

# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

# Collections
collections:
  snippets:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      excerpt:
        Souheil TAIEB a Software Enginner focusing on Web development and the .Net stack in particular.